### ISSUE TITLE
Comma in 7th line

### ISSUE THREAD

**Issue by ZZPot** [morae/color-transfer#1]
Should be
 #define fatalError(args, ...)

**Comment by morae** [comment]
This is a valid [variadic macro](http://gcc.gnu.org/onlinedocs/gcc-4.1.1/cpp/Variadic-Macros.html) in C++, where:

`#define fatalError(args...)` defines a variable argument list named `args`.
`#define fatalError(args, ...)` defines a positional argument `args` and then an anonymous variable argument list, accessible through `__VA_ARGS__`.

Since the purpose of this macro is to call `fprintf` with all of the arguments sent to the macro (string with format specifiers, and all remaining arguments), the first form is correct.

**Comment by ZZPot** [comment]
Ok, but it treated like error in Visual Studio 12.

**Comment by morae** [comment]
It is a GNU extension, so it will only work with GCC. For non-GNU implementations (like Visual Studio) you would have to replace it with the following form:

`#define fatalError(...)` and then use `__VA_ARGS__` in the body of the macro instead of the named `args`.
